/* eslint-disable @next/next/no-page-custom-font */
import Head from 'next/head'
import About from '../components/About'
import Layout from '../components/Layout'
import Me from '../components/Me'
import Work from '../components/Work'
import styles from '../styles/Home.module.css'
import {gsap} from 'gsap'
import {ScrollTrigger} from 'gsap/dist/ScrollTrigger'
import { useEffect } from 'react'

export default function Home() {
  gsap.registerPlugin(ScrollTrigger)

  useEffect(() =>{
    let sections = gsap.utils.toArray("section"), 
    currentSectiion = sections[0];

    console.log(currentSectiion)
  
    gsap.defaults({overwrite: 'auto', duration: 0.3});
  
    gsap.set("body", {height: (sections.length * 100) + "%"});
  
    sections.forEach((section, i) => {
      ScrollTrigger.create({
        start: () => (i - 0.5) * innerHeight,
        end: () => (i + 0.5) * innerHeight,
        onToggle: self => self.isActive && setSection(section)
      })
    })
  
    function setSection (newSection) {
      if (newSection !== currentSectiion) {
        gsap.to(currentSectiion, {scale: 0.8, autoAlpha: 0})
        gsap.to(newSection, {scale: 1, autoAlpha: 1})
        currentSectiion = newSection
      }
    }
  
    ScrollTrigger.create({
      start: 1,
      end: () => ScrollTrigger.maxScroll(window) - 1,
      onLeaveBack: self => self.scroll(ScrollTrigger.maxScroll(window) - 2),
      onLeave: self => self.scroll(2)
    }).scroll(2)
  }, [])
  
  return (
    <div className={styles.home}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link rel='preconnect' href='https://fonts.gstatic.com' crossOrigin />
        <link href='https://fonts.googleapis.com/css2?family=Scope+One&display=swap' rel='stylesheet' />
      </Head>

      <Layout>
        <Me />
        <About />
        <Work />
      </Layout>
    </div>
  )
}
